# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  # Temporary on current branch
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      MULE_EE_USERNAME: ${{ secrets.MULE_EE_USERNAME }}
      MULE_EE_PASSWORD: ${{ secrets.MULE_EE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: adopt-hotspot
          java-version: 8
          cache: maven
          server-id: mulesoft-ee-releases
          server-username: MULE_EE_USERNAME
          server-password: MULE_EE_PASSWORD
      - name: Verify
        # build to generate docs folder
        run: ./mvnw --batch-mode verify
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './mule-module/target/docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
